import { Product, Store } from '@/types/product';

/**
 * Mock data para productos Liqui.cl (limpieza y autocuidado)
 * En producción vendría de Open Beauty Facts / Open Products Facts + API local de precios
 */
export const MOCK_PRODUCTS: Product[] = [
  // LIMPIEZA
  {
    id: '1',
    barcode: '7802420100028',
    name: 'Detergente Líquido Concentrado 3L',
    brand: 'Popeye',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 3000,
      doses_per_package: 60,
      concentration: 'concentrado',
      biodegradable: true,
      phosphate_free: true,
      chlorine_free: true,
      certifications: ['Ecocert'],
    },
    labels: ['biodegradable', 'sin-fosfatos', 'concentrado'],
    eco_score: 82,
    social_score: 75,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 8990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    barcode: '7802420100035',
    name: 'Lavavajillas Biodegradable 500ml',
    brand: 'Biogreen',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 500,
      biodegradable: true,
      phosphate_free: true,
      fragrance_free: true,
      certifications: ['Ecocert', 'Vegan'],
    },
    labels: ['biodegradable', 'sin-fosfatos', 'vegano'],
    eco_score: 88,
    social_score: 82,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 180,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    barcode: '7802420100042',
    name: 'Limpiador Multiuso Ecológico 1L',
    brand: 'EcoClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 1000,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['Green Seal'],
    },
    labels: ['biodegradable', 'multiuso', 'sin-cloro'],
    eco_score: 85,
    social_score: 78,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 220,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    barcode: '7802420100059',
    name: 'Jabón Líquido para Ropa 2L',
    brand: 'Popeye',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 2000,
      doses_per_package: 40,
      concentration: 'normal',
      biodegradable: true,
      phosphate_free: true,
    },
    labels: ['biodegradable', 'sin-fosfatos'],
    eco_score: 79,
    social_score: 74,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 6990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 380,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    barcode: '7802420100066',
    name: 'Desinfectante Natural 750ml',
    brand: 'Biogreen',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 750,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['EPA Safer Choice'],
    },
    labels: ['biodegradable', 'desinfectante', 'natural'],
    eco_score: 86,
    social_score: 80,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 7490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 210,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    barcode: '7802420100073',
    name: 'Suavizante Hipoalergénico 1.5L',
    brand: 'Popeye',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 1500,
      biodegradable: true,
      fragrance_free: true,
      certifications: ['Dermatológicamente testado'],
    },
    labels: ['hipoalergénico', 'sin-fragancia', 'biodegradable'],
    eco_score: 81,
    social_score: 76,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 320,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    barcode: '7802420100080',
    name: 'Limpiador de Baño Ecológico 500ml',
    brand: 'EcoClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 500,
      biodegradable: true,
      chlorine_free: true,
    },
    labels: ['biodegradable', 'sin-cloro'],
    eco_score: 84,
    social_score: 77,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 165,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    barcode: '7802420100097',
    name: 'Quitamanchas Natural 400ml',
    brand: 'Biogreen',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 400,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['Ecocert'],
    },
    labels: ['biodegradable', 'natural', 'sin-cloro'],
    eco_score: 87,
    social_score: 81,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 150,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // INFANTIL Y BEBÉ
  {
    id: '9',
    barcode: '7802420200019',
    name: 'Pañales Ecológicos Talla M x40',
    brand: 'BabyGreen',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      cruelty_free: true,
      certifications: ['FSC', 'Dermatológicamente testado'],
    },
    labels: ['hipoalergénico', 'sin-cloro', 'biodegradable'],
    eco_score: 88,
    social_score: 85,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 12990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 280,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    barcode: '7802420200026',
    name: 'Pañales Ecológicos Talla G x36',
    brand: 'BabyGreen',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      certifications: ['FSC', 'Dermatológicamente testado'],
    },
    labels: ['hipoalergénico', 'sin-cloro', 'biodegradable'],
    eco_score: 87,
    social_score: 84,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 13990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 310,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    barcode: '7802420500010',
    name: 'Toallas Húmedas Biodegradables x80',
    brand: 'BabyCare',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'plástico biodegradable',
      package_recyclable: false,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      paraben_free: true,
      certifications: ['Dermatológicamente testado'],
    },
    labels: ['biodegradable', 'hipoalergénico', 'sin-alcohol'],
    eco_score: 78,
    social_score: 82,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 95,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    barcode: '7802420200033',
    name: 'Crema para Pañal Natural 100g',
    brand: 'BabyNature',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'tubo reciclable',
      package_recyclable: true,
      package_size_g: 100,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Vegan Society', 'Dermatológicamente testado'],
    },
    labels: ['vegano', 'cruelty-free', 'natural'],
    eco_score: 83,
    social_score: 88,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 6990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 85,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    barcode: '7802420200040',
    name: 'Jabón Líquido para Bebé 250ml',
    brand: 'BabyGreen',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 250,
      biodegradable: true,
      fragrance_free: true,
      paraben_free: true,
      certifications: ['Dermatológicamente testado'],
    },
    labels: ['hipoalergénico', 'sin-fragancia', 'pH neutro'],
    eco_score: 85,
    social_score: 83,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 110,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    barcode: '7802420200057',
    name: 'Shampoo para Bebé Sin Lágrimas 300ml',
    brand: 'BabyCare',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 300,
      paraben_free: true,
      fragrance_free: true,
      certifications: ['Dermatológicamente testado'],
    },
    labels: ['hipoalergénico', 'sin-lágrimas', 'suave'],
    eco_score: 80,
    social_score: 81,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 125,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // CUIDADO PERSONAL
  {
    id: '15',
    barcode: '7802420300016',
    name: 'Shampoo Natural Sin Sulfatos 400ml',
    brand: 'NaturalCare',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 400,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      fragrance_free: false,
      certifications: ['Leaping Bunny', 'Vegan Society'],
    },
    labels: ['vegano', 'cruelty-free', 'sin-parabenos', 'sin-sulfatos'],
    eco_score: 85,
    social_score: 92,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 6990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 180,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    barcode: '7802420300023',
    name: 'Acondicionador Natural 400ml',
    brand: 'NaturalCare',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 400,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Leaping Bunny', 'Vegan Society'],
    },
    labels: ['vegano', 'cruelty-free', 'sin-parabenos'],
    eco_score: 84,
    social_score: 91,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 7490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 185,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    barcode: '7802420300030',
    name: 'Jabón en Barra Natural 100g',
    brand: 'PuraSoap',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      package_size_g: 100,
      vegan: true,
      cruelty_free: true,
      biodegradable: true,
      certifications: ['Vegan', 'Cruelty-free'],
    },
    labels: ['vegano', 'artesanal', 'biodegradable'],
    eco_score: 92,
    social_score: 89,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 45,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '18',
    barcode: '7802420300047',
    name: 'Desodorante Natural Sin Aluminio 75g',
    brand: 'EcoDeo',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      package_size_g: 75,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Vegan', 'Natural'],
    },
    labels: ['vegano', 'sin-aluminio', 'natural'],
    eco_score: 90,
    social_score: 87,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 60,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '19',
    barcode: '7802420300054',
    name: 'Crema Hidratante Facial 50ml',
    brand: 'NaturalSkin',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio',
      package_recyclable: true,
      package_size_ml: 50,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Ecocert', 'Cosmos Organic'],
    },
    labels: ['orgánico', 'vegano', 'cruelty-free'],
    eco_score: 88,
    social_score: 93,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 12990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 140,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '20',
    barcode: '7802420300061',
    name: 'Pasta Dental Natural 100g',
    brand: 'SmileGreen',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'tubo reciclable',
      package_recyclable: true,
      package_size_g: 100,
      vegan: true,
      cruelty_free: true,
      certifications: ['Vegan', 'Natural'],
    },
    labels: ['vegano', 'sin-flúor', 'natural'],
    eco_score: 86,
    social_score: 85,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '21',
    barcode: '7802420300078',
    name: 'Gel de Ducha Orgánico 500ml',
    brand: 'PuraEssence',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 500,
      vegan: true,
      cruelty_free: true,
      biodegradable: true,
      certifications: ['Ecocert', 'Vegan'],
    },
    labels: ['orgánico', 'vegano', 'biodegradable'],
    eco_score: 87,
    social_score: 90,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 7990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 195,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22',
    barcode: '7802420300085',
    name: 'Protector Solar Mineral SPF50 100ml',
    brand: 'SunSafe',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'plástico reciclable',
      package_recyclable: true,
      package_size_ml: 100,
      biodegradable: true,
      paraben_free: true,
      certifications: ['Reef Safe', 'Dermatológicamente testado'],
    },
    labels: ['reef-safe', 'mineral', 'biodegradable'],
    eco_score: 82,
    social_score: 84,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 9990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 145,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '23',
    barcode: '7802420300092',
    name: 'Exfoliante Corporal Natural 200g',
    brand: 'BodyNature',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio',
      package_recyclable: true,
      package_size_g: 200,
      vegan: true,
      cruelty_free: true,
      biodegradable: true,
      certifications: ['Vegan', 'Organic'],
    },
    labels: ['vegano', 'orgánico', 'artesanal'],
    eco_score: 89,
    social_score: 88,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 8490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 165,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '24',
    barcode: '7802420300108',
    name: 'Aceite Corporal Nutritivo 100ml',
    brand: 'NaturalSkin',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio',
      package_recyclable: true,
      package_size_ml: 100,
      vegan: true,
      cruelty_free: true,
      certifications: ['Ecocert', 'Organic'],
    },
    labels: ['orgánico', 'vegano', '100% natural'],
    eco_score: 91,
    social_score: 92,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 11990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 155,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '25',
    barcode: '7802420300115',
    name: 'Champú Sólido Sin Envase 80g',
    brand: 'ZeroWaste',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'sin envase',
      package_recyclable: true,
      package_size_g: 80,
      vegan: true,
      cruelty_free: true,
      biodegradable: true,
      certifications: ['Vegan', 'Zero Waste'],
    },
    labels: ['zero-waste', 'vegano', 'sólido'],
    eco_score: 95,
    social_score: 90,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 6490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 35,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // PAPELES
  {
    id: '26',
    barcode: '7802420400013',
    name: 'Papel Higiénico Bambú 4 Rollos',
    brand: 'EcoPapel',
    category: 'Papeles',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC', 'Rainforest Alliance'],
    },
    labels: ['bambú', 'sin-cloro', 'biodegradable', '100% reciclable'],
    eco_score: 90,
    social_score: 80,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 120,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '27',
    barcode: '7802420400020',
    name: 'Papel Higiénico Reciclado 8 Rollos',
    brand: 'GreenPaper',
    category: 'Papeles',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC 100% Reciclado'],
    },
    labels: ['reciclado', 'sin-cloro', 'biodegradable'],
    eco_score: 88,
    social_score: 78,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 145,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '28',
    barcode: '7802420400037',
    name: 'Toallas de Papel Bambú x2',
    brand: 'EcoPapel',
    category: 'Papeles',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC'],
    },
    labels: ['bambú', 'absorbente', 'biodegradable'],
    eco_score: 87,
    social_score: 79,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 95,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '29',
    barcode: '7802420400044',
    name: 'Servilletas Recicladas x100',
    brand: 'GreenPaper',
    category: 'Papeles',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC'],
    },
    labels: ['reciclado', 'sin-cloro', 'compostable'],
    eco_score: 85,
    social_score: 77,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 2490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 65,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '30',
    barcode: '7802420400051',
    name: 'Pañuelos Faciales Bambú x6',
    brand: 'EcoPapel',
    category: 'Papeles',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC', 'Dermatológicamente testado'],
    },
    labels: ['bambú', 'suave', 'hipoalergénico'],
    eco_score: 86,
    social_score: 80,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 110,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // CUIDADO ADULTO
  {
    id: '31',
    barcode: '7802420600017',
    name: 'Toallas Higiénicas Orgánicas x12',
    brand: 'NaturalCare',
    category: 'Cuidado adulto',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      certifications: ['GOTS', 'Dermatológicamente testado'],
    },
    labels: ['orgánico', 'sin-cloro', 'biodegradable'],
    eco_score: 89,
    social_score: 86,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 6990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 135,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '32',
    barcode: '7802420600024',
    name: 'Copa Menstrual Silicona Médica',
    brand: 'EcoFem',
    category: 'Cuidado adulto',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      vegan: true,
      certifications: ['FDA Aprobado', 'Silicona médica'],
    },
    labels: ['reutilizable', 'eco-friendly', 'hipoalergénico'],
    eco_score: 96,
    social_score: 90,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 19990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 95,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '33',
    barcode: '7802420600031',
    name: 'Protectores Diarios Orgánicos x30',
    brand: 'NaturalCare',
    category: 'Cuidado adulto',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      certifications: ['GOTS'],
    },
    labels: ['orgánico', 'sin-cloro', 'biodegradable'],
    eco_score: 87,
    social_score: 84,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 85,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OUTLET Y OTROS
  {
    id: '34',
    barcode: '7802420700014',
    name: 'Kit Cero Residuos Básico',
    brand: 'ZeroWaste',
    category: 'Outlet',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      vegan: true,
      cruelty_free: true,
      certifications: ['Zero Waste'],
    },
    labels: ['kit', 'zero-waste', 'reutilizable'],
    eco_score: 93,
    social_score: 88,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 24990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 220,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '35',
    barcode: '7802420100104',
    name: 'Detergente Ultra Concentrado 1L',
    brand: 'EcoClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 1000,
      doses_per_package: 50,
      concentration: 'ultra-concentrado',
      biodegradable: true,
      phosphate_free: true,
      certifications: ['Ecocert', 'EU Ecolabel'],
    },
    labels: ['ultra-concentrado', 'biodegradable', 'sin-fosfatos'],
    eco_score: 91,
    social_score: 83,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 9990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 195,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '36',
    barcode: '7802420100111',
    name: 'Limpiador de Vidrios Ecológico 500ml',
    brand: 'Biogreen',
    category: 'Limpieza',
    product_info: {
      package_type: 'plástico reciclado',
      package_recyclable: true,
      package_size_ml: 500,
      biodegradable: true,
      fragrance_free: true,
    },
    labels: ['biodegradable', 'sin-rayas', 'sin-fragancia'],
    eco_score: 83,
    social_score: 79,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 155,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '37',
    barcode: '7802420100128',
    name: 'Cera para Muebles Natural 250ml',
    brand: 'WoodCare',
    category: 'Limpieza',
    product_info: {
      package_type: 'lata reciclable',
      package_recyclable: true,
      package_size_ml: 250,
      biodegradable: true,
      vegan: true,
    },
    labels: ['natural', 'vegano', 'sin-químicos'],
    eco_score: 88,
    social_score: 81,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 7490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 175,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '38',
    barcode: '7802420300122',
    name: 'Mascarilla Capilar Orgánica 200ml',
    brand: 'HairNature',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio',
      package_recyclable: true,
      package_size_ml: 200,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Ecocert', 'Cosmos Organic'],
    },
    labels: ['orgánico', 'vegano', 'reparador'],
    eco_score: 86,
    social_score: 89,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 9990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 190,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '39',
    barcode: '7802420300139',
    name: 'Sérum Facial Vitamina C 30ml',
    brand: 'NaturalSkin',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio oscuro',
      package_recyclable: true,
      package_size_ml: 30,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Ecocert'],
    },
    labels: ['anti-edad', 'vegano', 'vitamina-c'],
    eco_score: 85,
    social_score: 91,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 14990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 125,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '40',
    barcode: '7802420300146',
    name: 'Bálsamo Labial Natural SPF15',
    brand: 'LipCare',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      package_size_g: 4.5,
      vegan: true,
      cruelty_free: true,
      certifications: ['Vegan', 'Reef Safe'],
    },
    labels: ['vegano', 'SPF15', 'natural'],
    eco_score: 89,
    social_score: 87,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 35,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '41',
    barcode: '7802420200064',
    name: 'Pañales Nocturnos Ecológicos x32',
    brand: 'BabyGreen',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      fragrance_free: true,
      certifications: ['FSC', 'Dermatológicamente testado'],
    },
    labels: ['nocturno', 'biodegradable', 'extra-absorbente'],
    eco_score: 86,
    social_score: 83,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 14990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 295,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '42',
    barcode: '7802420200071',
    name: 'Aceite para Masajes Bebé 150ml',
    brand: 'BabyNature',
    category: 'Infantil y bebé',
    product_info: {
      package_type: 'vidrio',
      package_recyclable: true,
      package_size_ml: 150,
      vegan: true,
      cruelty_free: true,
      paraben_free: true,
      certifications: ['Organic', 'Dermatológicamente testado'],
    },
    labels: ['orgánico', 'hipoalergénico', 'natural'],
    eco_score: 87,
    social_score: 86,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 8990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 165,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '43',
    barcode: '7802420100135',
    name: 'Bloques WC Ecológicos x3',
    brand: 'EcoClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['Ecocert'],
    },
    labels: ['biodegradable', 'aroma-natural', 'sin-cloro'],
    eco_score: 84,
    social_score: 78,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 95,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '44',
    barcode: '7802420100142',
    name: 'Esponjas Biodegradables x4',
    brand: 'GreenClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      vegan: true,
      certifications: ['Compostable'],
    },
    labels: ['biodegradable', 'compostable', 'vegano'],
    eco_score: 92,
    social_score: 85,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 3990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 55,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '45',
    barcode: '7802420300153',
    name: 'Cepillo de Dientes Bambú',
    brand: 'EcoDental',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      biodegradable: true,
      vegan: true,
      certifications: ['FSC', 'Biodegradable'],
    },
    labels: ['bambú', 'biodegradable', 'zero-waste'],
    eco_score: 94,
    social_score: 88,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 2990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 25,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '46',
    barcode: '7802420300160',
    name: 'Hilo Dental Natural 50m',
    brand: 'SmileGreen',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'vidrio reutilizable',
      package_recyclable: true,
      biodegradable: true,
      vegan: true,
      certifications: ['Compostable'],
    },
    labels: ['biodegradable', 'compostable', 'vegano'],
    eco_score: 91,
    social_score: 86,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 4490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 40,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '47',
    barcode: '7802420400068',
    name: 'Papel Higiénico Triple Hoja x6',
    brand: 'EcoPapel',
    category: 'Papeles',
    product_info: {
      package_type: 'papel reciclado',
      package_recyclable: true,
      biodegradable: true,
      chlorine_free: true,
      certifications: ['FSC', 'Nordic Swan'],
    },
    labels: ['bambú', 'triple-hoja', 'suave'],
    eco_score: 88,
    social_score: 81,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 5490,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 135,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '48',
    barcode: '7802420100159',
    name: 'Detergente en Cápsulas x30',
    brand: 'EcoClean',
    category: 'Limpieza',
    product_info: {
      package_type: 'cartón reciclable',
      package_recyclable: true,
      doses_per_package: 30,
      concentration: 'concentrado',
      biodegradable: true,
      phosphate_free: true,
      certifications: ['Ecocert'],
    },
    labels: ['cápsulas', 'biodegradable', 'pre-dosificado'],
    eco_score: 85,
    social_score: 80,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 11990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 265,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '49',
    barcode: '7802420300177',
    name: 'Set Cosmética Sólida Viaje',
    brand: 'ZeroWaste',
    category: 'Cuidado personal',
    product_info: {
      package_type: 'lata reciclable',
      package_recyclable: true,
      vegan: true,
      cruelty_free: true,
      biodegradable: true,
      certifications: ['Vegan', 'Zero Waste'],
    },
    labels: ['zero-waste', 'sólido', 'viaje'],
    eco_score: 93,
    social_score: 89,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 16990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 115,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '50',
    barcode: '7802420600048',
    name: 'Paños Reutilizables x6',
    brand: 'EcoFem',
    category: 'Cuidado adulto',
    product_info: {
      package_type: 'bolsa tela',
      package_recyclable: true,
      biodegradable: true,
      vegan: true,
      certifications: ['GOTS', 'Oeko-Tex'],
    },
    labels: ['reutilizable', 'lavable', 'orgánico'],
    eco_score: 95,
    social_score: 91,
    image_url: '/placeholder.svg',
    last_seen_price_clp: 22990,
    last_vendor: 'Liqui.cl',
    carbon_gco2e: 145,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_STORES: Store[] = [
  {
    id: '1',
    name: 'Jumbo Kennedy',
    address: 'Av. Kennedy 9001, Las Condes',
    lat: -33.4042,
    lon: -70.5735,
    vendor_code: 'JUMBO',
  },
  {
    id: '2',
    name: 'Lider Express Providencia',
    address: 'Av. Providencia 2331, Providencia',
    lat: -33.4264,
    lon: -70.6106,
    vendor_code: 'LIDER',
  },
  {
    id: '3',
    name: 'Unimarc Bellavista',
    address: 'Pío Nono 355, Recoleta',
    lat: -33.4342,
    lon: -70.6356,
    vendor_code: 'UNIMARC',
  },
  {
    id: '4',
    name: 'Santa Isabel Ñuñoa',
    address: 'Av. Irarrázaval 3850, Ñuñoa',
    lat: -33.4568,
    lon: -70.5986,
    vendor_code: 'SANTA_ISABEL',
  },
];

/**
 * Search products by query and category
 */
export const searchProducts = (query: string, category?: string): Product[] => {
  let results = MOCK_PRODUCTS;
  
  if (query) {
    const lowerQuery = query.toLowerCase();
    results = results.filter(
      (p) =>
        p.name.toLowerCase().includes(lowerQuery) ||
        p.brand.toLowerCase().includes(lowerQuery) ||
        p.barcode.includes(lowerQuery)
    );
  }
  
  if (category) {
    results = results.filter((p) => p.category === category);
  }
  
  return results;
};

/**
 * Get product by barcode
 */
export const getProductByBarcode = (barcode: string): Product | undefined => {
  return MOCK_PRODUCTS.find((p) => p.barcode === barcode);
};

/**
 * Get categories
 */
export const getCategories = (): string[] => {
  return Array.from(new Set(MOCK_PRODUCTS.map((p) => p.category)));
};
