project_id = "dwdtoduxzegssuyruksm"

[functions.optimize-knapsack]
verify_jwt = true

[functions.fetch-product-info]
verify_jwt = false

[functions.geocode-stores]
verify_jwt = false

[functions.calculate-carbon]
verify_jwt = false